import { useCallback, useEffect, useRef, useState } from "react";
import type { GenerateReportResponse } from "../types/report";

type Props = { report: GenerateReportResponse };

function tableName(fqn: string) {
  const parts = fqn.split(".");
  return parts[parts.length - 1] ?? fqn;
}

export function ShareActions({ report }: Props) {
  const [copied, setCopied] = useState<string | null>(null);
  const [copyError, setCopyError] = useState<string | null>(null);
  const resetTimerRef = useRef<number | null>(null);

  useEffect(() => () => {
    if (resetTimerRef.current !== null) window.clearTimeout(resetTimerRef.current);
  }, []);

  const copy = useCallback(async (text: string, key: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(key);
      setCopyError(null);
      if (resetTimerRef.current !== null) window.clearTimeout(resetTimerRef.current);
      resetTimerRef.current = window.setTimeout(() => {
        setCopied(null);
        resetTimerRef.current = null;
      }, 1600);
    } catch {
      setCopyError("Clipboard permission denied.");
    }
  }, []);

  const name = tableName(report.tableFQN);
  const fails = report.failedTests.length;
  const downs = report.lineage.downstream.length;
  const sev = report.severity ?? "UNKNOWN";

  const slackText =
    `🚨 *[${sev}] Data Incident: ${name}*\n` +
    `${fails} quality test(s) failed · ${downs} downstream table(s) at risk\n` +
    `\`${report.tableFQN}\`\n` +
    `_Generated by DataStory_`;

  const ghTitle = `[${sev}] Data incident: ${name} — ${fails} failing test(s)`;
  const ghBody =
    `## Summary\n\n${report.summary ?? ""}\n\n` +
    `**Severity:** ${sev}\n**Table:** \`${report.tableFQN}\`\n\n` +
    `## Report\n\n${report.markdown}`;

  const jiraTitle = `[${sev}] ${name}: ${fails} failing test(s), ${downs} downstream tables affected`;

  const actions = [
    { key: "slack", label: "Slack message", text: slackText, icon: "💬" },
    {
      key: "github",
      label: "GitHub issue body",
      text: `# ${ghTitle}\n\n${ghBody}`,
      icon: "🐙",
    },
    { key: "jira", label: "JIRA ticket title", text: jiraTitle, icon: "📋" },
  ];

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/40 p-4">
      <div className="text-sm font-semibold text-slate-200">Share</div>
      <div className="sr-only" aria-live="polite" role="status">
        {copyError ? copyError : copied ? `Copied ${copied} text` : ""}
      </div>
      {copyError ? <div className="mt-2 text-xs text-amber-300">{copyError}</div> : null}
      <div className="mt-3 flex flex-col gap-2">
        {actions.map((a) => (
          <button
            key={a.key}
            type="button"
            onClick={() => copy(a.text, a.key)}
            className="flex w-full items-center justify-between rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-medium text-slate-300 transition-colors hover:border-indigo-500/50 hover:text-indigo-200"
          >
            <span className="flex items-center gap-2">
              <span>{a.icon}</span>
              <span>Copy {a.label}</span>
            </span>
            <span
              className={`transition-colors ${
                copied === a.key ? "text-emerald-400" : "text-slate-600"
              }`}
            >
              {copied === a.key ? "✓ Copied" : "Copy"}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}
